import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "react-hot-toast";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="h-full antialiased" 
    data-coolstyles-extension="installed" data-coolstyles-extension-version="1.9.0"
    >
      <body>
        {children}


      <Toaster position="top-right" />
      </body>
    </html>
  );
}
